from abc import ABCMeta, abstractmethod
import datetime
# 看你是python2 还是 python3了
try:
    import Queue as queue
except ImportError:
    import queue
    
import numpy as np
import pandas as pd

from event import SignalEvent

class Strategy(object):
    """
    Strategy is an abstract base class providingan interface for all subsequent(inherirted) strategu handling objects.
    The goal of a derived Strategy object is to generate Signal objects for particular symbols based on the inputs of 
    Bars generated by a DataHandler object.
    """
    __metaclass__ = ABCMeta
    
    @abstractmethod
    def calculate_signals(self):
        """
        provides the mechanisms to calculate the list of signals.
        """
        raise NotImplementedError("Should implement calculate_signals()")
    
    